import type { Metadata } from "next";
import { HydrateClient, api } from "@/trpc/server";
import { RateDetailClient } from "./rate-detail-client";
import { notFound } from "next/navigation";
import { getTranslation } from "@/lib/i18n";

export const dynamic = "auto";

// ISR with 5 minutes revalidation (rate content rarely changes)
export const revalidate = 300;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}): Promise<Metadata> {
  const { lng, id } = await params;

  // Parallel fetch: translation and rate data
  const [{ t }, rate] = await Promise.all([
    getTranslation(lng),
    api.rate.detail({ id }).catch(() => null),
  ]);

  if (!rate) {
    return {
      title: "Rate - Dicecho",
      description: "TRPG review on Dicecho",
    };
  }

  const modTitle = rate.mod?.title ?? "TRPG";
  const userName = rate.user.nickName;
  const ratingText = rate.rate ? `★${rate.rate.toFixed(1)}` : "";

  // Use i18n for title and description
  const rateTitle = t("metadata.rate.title", { user: userName, mod: modTitle });
  const ogTitle = ratingText
    ? t("metadata.rate.ogTitle", { rating: ratingText, user: userName, mod: modTitle })
    : t("metadata.rate.ogTitleNoRating", { user: userName, mod: modTitle });
  const description =
    rate.remark?.slice(0, 160) ||
    t("metadata.rate.description", { user: userName, mod: modTitle });

  // OG image is auto-generated by opengraph-image.tsx
  return {
    title: rateTitle,
    description,
    openGraph: {
      title: ogTitle,
      description,
      url: `/${lng}/rate/${id}`,
      type: "article",
      siteName: "Dicecho",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
    },
  };
}

const RateDetailPage = async (props: {
  params: Promise<{ lng: string; id: string }>;
}) => {
  const params = await props.params;
  const { lng, id } = params;

  // Server-side: fetch public data (no userId)
  const rate = await api.rate.detail({ id }).catch(() => null);

  if (!rate) {
    return notFound();
  }

  // JSON-LD structured data for Google rich snippets
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Review",
    "@id": `https://dicecho.com/${lng}/rate/${id}`,
    url: `https://dicecho.com/${lng}/rate/${id}`,
    itemReviewed: rate.mod
      ? {
          "@type": "Game",
          name: rate.mod.title,
          url: `https://dicecho.com/${lng}/scenario/${rate.mod._id}`,
        }
      : undefined,
    author: {
      "@type": "Person",
      name: rate.user.nickName,
    },
    ...(rate.rate && {
      reviewRating: {
        "@type": "Rating",
        ratingValue: rate.rate,
        bestRating: 10,
        worstRating: 0,
      },
    }),
    ...(rate.remark && {
      reviewBody: rate.remark,
    }),
    datePublished: rate.createdAt,
  };

  return (
    <HydrateClient>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <div className="md:container grid grid-cols-6 gap-8">
        <div className="col-span-6 md:col-span-4">
          <RateDetailClient rateId={id} />
        </div>
      </div>
    </HydrateClient>
  );
};

export default RateDetailPage;
