import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getDicechoServerApi } from "@/server/dicecho";
import { TopicDetailClient } from "./topic-detail-client";
import { TopicDetailHeader } from "./topic-detail-header";

export const dynamic = "auto";
export const revalidate = 60;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}): Promise<Metadata> {
  // Parallel: parse params and get API client
  const [{ id, lng }, api] = await Promise.all([
    params,
    getDicechoServerApi(),
  ]);

  const topic = await api.topic.detail(id, { revalidate: 60 }).catch(() => null);

  if (!topic) {
    return {
      title: "Topic - Dicecho",
      description: "Forum topic on Dicecho",
    };
  }

  const topicTitle = topic.title;
  const description = topic.content.slice(0, 160);
  // Optimize title for OG (50-60 chars)
  const ogTitle = `${topicTitle} | Dicecho Forum`;

  // OG image is auto-generated by opengraph-image.tsx
  return {
    title: topicTitle,
    description,
    openGraph: {
      title: ogTitle,
      description,
      url: `/${lng}/forum/topic/${id}`,
      type: "article",
      siteName: "Dicecho",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
    },
    alternates: {
      canonical: `/${lng}/forum/topic/${id}`,
      languages: {
        en: `/en/forum/topic/${id}`,
        ja: `/ja/forum/topic/${id}`,
        zh: `/zh/forum/topic/${id}`,
        ko: `/ko/forum/topic/${id}`,
      },
    },
  };
}

export default async function TopicDetailPage({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}) {
  // Parallel: parse params and get API client
  const [{ lng, id }, api] = await Promise.all([
    params,
    getDicechoServerApi(),
  ]);

  const topic = await api.topic.detail(id, { revalidate: 60 }).catch(() => null);

  if (!topic) {
    return notFound();
  }

  return (
    <>
      <TopicDetailHeader title={topic.title} />

      <div className="md:container pt-14 md:pt-4">
        <TopicDetailClient topic={topic} lng={lng} />
      </div>
    </>
  );
}
