import type { Metadata } from "next";
import { ScenarioDetail } from "./scenario-detail";
import { ScenarioDetailHeader } from "./header";
import { getDicechoServerApi } from "@/server/dicecho";
import { notFound } from "next/navigation";

// Let Next.js decide the rendering strategy based on usage
export const dynamic = "auto";

// ISR with 5 minutes revalidation (scenario details change less frequently)
export const revalidate = 300;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}): Promise<Metadata> {
  const { lng, id } = await params;

  // Start API client fetch early
  const api = await getDicechoServerApi();
  const scenario = await api.module.detail(id, { revalidate: 300 }).catch(() => null);
  if (!scenario) {
    return {
      title: "Scenario - Dicecho",
      description: "TRPG scenario on Dicecho",
    };
  }

  const scenarioTitle = scenario.originTitle || scenario.title;
  const baseDescription =
    scenario.description || `${scenario.title} - TRPG scenario on Dicecho`;

  // Build OG title with rating if available (optimal: 50-60 chars)
  const ratingPrefix =
    scenario.rateCount > 0 ? `★${scenario.rateAvg.toFixed(1)} ` : "";
  const ogTitle = `${ratingPrefix}${scenarioTitle} | Dicecho TRPG`;

  // Build OG description (optimal: 110-160 chars)
  const ratingInfo =
    scenario.rateCount > 0
      ? `${scenario.rateAvg.toFixed(1)}/10 (${scenario.rateCount}条评价)`
      : "";
  const ruleInfo = scenario.moduleRule ? `规则: ${scenario.moduleRule}` : "";
  const playerInfo = scenario.playerNumber
    ? `人数: ${scenario.playerNumber[0]}-${scenario.playerNumber[1]}人`
    : "";
  const metaInfo = [ratingInfo, ruleInfo, playerInfo].filter(Boolean).join(" | ");
  const truncatedDesc = baseDescription.slice(0, 120);
  const ogDescription = metaInfo
    ? `${metaInfo} - ${truncatedDesc}`.slice(0, 160)
    : truncatedDesc.slice(0, 160);

  // OG image is auto-generated by opengraph-image.tsx
  return {
    title: scenarioTitle,
    description: baseDescription.slice(0, 160),
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: `/${lng}/scenario/${id}`,
      type: "article",
      siteName: "Dicecho",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: ogDescription,
    },
  };
}

const ScenarioDetailPage = async ({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}) => {
  // Parallel: parse params and get API client
  const [{ lng, id }, api] = await Promise.all([
    params,
    getDicechoServerApi(),
  ]);

  // Server-side data fetching with 300s (5min) revalidation cache
  // Scenario details change less frequently than lists
  const scenario = await api.module.detail(id, { revalidate: 300 }).catch(() => null);

  if (!scenario) {
    return notFound();
  }

  // Generate JSON-LD structured data for Google rich snippets
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Game",
    "@id": `https://dicecho.com/${lng}/scenario/${id}`,
    url: `https://dicecho.com/${lng}/scenario/${id}`,
    name: scenario.originTitle || scenario.title,
    description: scenario.description || `${scenario.title} - TRPG scenario`,
    image: scenario.coverUrl,
    ...(scenario.rateCount > 0 && {
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: scenario.rateAvg,
        bestRating: 10,
        worstRating: 0,
        ratingCount: scenario.rateCount,
      },
    }),
    ...(scenario.releaseDate && {
      datePublished: scenario.releaseDate,
    }),
    ...(scenario.moduleRule && {
      genre: scenario.moduleRule,
    }),
    ...(scenario.playerNumber && {
      numberOfPlayers: {
        "@type": "QuantitativeValue",
        minValue: scenario.playerNumber[0],
        maxValue: scenario.playerNumber[1],
      },
    }),
  };

  return (
    <>
      {/* JSON-LD for Google Rich Snippets */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <ScenarioDetailHeader title={scenario.title} scenario={scenario} />
      <ScenarioDetail lng={lng} scenario={scenario} />
    </>
  );
};

export default ScenarioDetailPage;
