import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import { Header } from '@/components/Header' 
import { Toaster } from "@/components/ui/toaster";
import { Layout as AppLayout } from "@/components/Layout";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
        <TRPCReactProvider>
          <AppLayout>
            <body className="bg-custom-gradient min-h-[100vh] bg-no-repeat">
              <Header />
              {children}
              <Toaster />
            </body>
          </AppLayout>
        </TRPCReactProvider>
    </html>
  );
}
