import type { Metadata } from "next";
import { AccountPageLayout } from "@/components/Account/account-page-layout";
import { AccountHome } from "@/components/Account/AccountHome";
import { MobileFooter } from "@/components/Footer";
import { getDicechoServerApi } from "@/server/dicecho";
import { notFound } from "next/navigation";

// Let Next.js decide the rendering strategy based on usage
export const dynamic = "auto";

// ISR with 60 seconds revalidation
export const revalidate = 60;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}): Promise<Metadata> {
  const { lng, id } = await params;

  const api = await getDicechoServerApi();
  const user = await api.user.profile(id, { revalidate: 60 }).catch(() => null);

  if (!user) {
    return {
      title: "User - Dicecho",
      description: "User profile on Dicecho",
    };
  }

  const accountTitle = `${user.nickName} | Dicecho`;
  // Optimize title for OG (50-60 chars)
  const ogTitle = `${user.nickName} - TRPG Player Profile | Dicecho`;
  const description = user.note || `${user.nickName}'s profile on Dicecho - TRPG community member`;

  // OG image is auto-generated by opengraph-image.tsx
  return {
    title: accountTitle,
    description,
    openGraph: {
      title: ogTitle,
      description,
      url: `/${lng}/account/${id}`,
      type: "profile",
      siteName: "Dicecho",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
    },
  };
}

export default async function AccountDetailPage(props: {
  params: Promise<{ lng: string; id: string }>;
}) {
  const params = await props.params;
  const { lng, id } = params;

  const api = await getDicechoServerApi();
  const user = await api.user.profile(id, { revalidate: 300 }).catch(() => null);

  if (!user) {
    notFound();
  }

  return (
    <>
      <AccountPageLayout user={user} lng={lng}>
        <div className="container py-4">
          <AccountHome user={user} />
        </div>
      </AccountPageLayout>
      <MobileFooter />
    </>
  );
}
