import type { Metadata } from "next";
import { AccountPageLayout } from "@/components/Account/account-page-layout";
import { MobileFooter } from "@/components/Footer";
import { getDicechoServerApi } from "@/server/dicecho";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AccountScenarios } from "@/components/Account/account-scenarios";
import { AccountRateList } from "@/components/Account/account-rate-list";
import { RichTextPreview } from "@/components/Editor";

import { notFound } from "next/navigation";
import { getTranslation } from "@/lib/i18n";

// Let Next.js decide the rendering strategy based on usage
export const dynamic = "auto";

// ISR with 60 seconds revalidation
export const revalidate = 60;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string; id: string }>;
}): Promise<Metadata> {
  const { lng, id } = await params;

  const api = await getDicechoServerApi();
  const user = await api.user.profile(id, { revalidate: 60 }).catch(() => null);

  if (!user) {
    return {
      title: "User - Dicecho",
      description: "User profile on Dicecho",
    };
  }

  const accountTitle = `${user.nickName} | Dicecho`;
  // Optimize title for OG (50-60 chars)
  const ogTitle = `${user.nickName} - TRPG Player Profile | Dicecho`;
  const description =
    user.note ||
    `${user.nickName}'s profile on Dicecho - TRPG community member`;

  // OG image is auto-generated by opengraph-image.tsx
  return {
    title: accountTitle,
    description,
    openGraph: {
      title: ogTitle,
      description,
      url: `/${lng}/account/${id}`,
      type: "profile",
      siteName: "Dicecho",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
    },
  };
}

export default async function AccountDetailPage(props: {
  params: Promise<{ lng: string; id: string }>;
}) {
  const params = await props.params;
  const { lng, id } = params;
  const { t } = await getTranslation(lng);
  const api = await getDicechoServerApi();
  const user = await api.user
    .profile(id, { revalidate: 300 })
    .catch(() => null);

  if (!user) {
    notFound();
  }

  const renderNotice = () =>
    user.notice ? (
      <RichTextPreview markdown={user.notice} />
    ) : (
      <div className="text-muted-foreground">{t("profile_notice_empty")}</div>
    );

  return (
    <>
      <AccountPageLayout user={user} lng={lng}>
        <div className="container py-4">
          <div className="grid gap-4 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
            <div className="flex flex-col gap-4">
              <Card className="md:hidden">
                <CardHeader>
                  <CardTitle>{t("profile_about")}</CardTitle>
                </CardHeader>
                <CardContent>{renderNotice()}</CardContent>
              </Card>

              <AccountScenarios user={user} />

              <AccountRateList userId={user._id} rateCount={user.rateCount} />
            </div>

            <div className="hidden md:block">
              <Card>
                <CardHeader>
                  <CardTitle>{t("profile_about")}</CardTitle>
                </CardHeader>
                <CardContent>{renderNotice()}</CardContent>
              </Card>
            </div>
          </div>
        </div>
      </AccountPageLayout>
      <MobileFooter />
    </>
  );
}
