import "@/styles/globals.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Analytics } from "@vercel/analytics/next";
import { GoogleAnalytics } from "@next/third-parties/google";
import { dir } from "i18next";
import { ThemeProvider } from "next-themes";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import { Layout as AppLayout } from "@/components/Layout";
import { languages } from "@/lib/i18n/settings";
import { ThemeScript } from "@/components/theme-script";
import { env } from "@/env";
import { getTranslation } from "@/lib/i18n";

export const dynamic = "force-static";

const localeMap: Record<string, string> = {
  en: "en_US",
  zh: "zh_CN",
  ja: "ja_JP",
  ko: "ko_KR",
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lng: string }>;
}): Promise<Metadata> {
  const { lng } = await params;
  const { t } = await getTranslation(lng);

  const title = t("metadata.title");
  const description = t("metadata.description");
  const ogTitle = t("metadata.ogTitle");
  const ogDescription = t("metadata.ogDescription");
  const locale = localeMap[lng] ?? "en_US";

  // OG image is auto-generated by opengraph-image.tsx
  return {
    metadataBase: new URL(
      process.env.VERCEL_URL
        ? `https://${process.env.VERCEL_URL}`
        : "https://dicecho.com"
    ),
    title,
    description,
    icons: [{ rel: "icon", url: "/favicon.ico" }],
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: `/${lng}`,
      siteName: "Dicecho",
      type: "website",
      locale,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: ogDescription,
    },
    alternates: {
      canonical: `/${lng}`,
      languages: {
        en: "/en",
        zh: "/zh",
        ja: "/ja",
        ko: "/ko",
      },
    },
  };
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}) {
  const params = await props.params;

  const { lng } = params;

  const { children } = props;

  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={GeistSans.variable}
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
      </head>
      <body className="bg-custom-gradient min-h-screen overflow-x-hidden bg-no-repeat">
        <NuqsAdapter>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <AppLayout>
              <Header lng={lng} />
              {children}
              <Analytics />
              <Toaster richColors position="top-center" />
            </AppLayout>
          </ThemeProvider>
        </NuqsAdapter>
        {env.NEXT_PUBLIC_GA_ID && (
          <GoogleAnalytics gaId={env.NEXT_PUBLIC_GA_ID} />
        )}
      </body>
    </html>
  );
}
